### ISSUE TITLE
Grocery Category Items Not Being Maintained

### ISSUE THREAD

**Issue by azamsharp** [EARoa/GroceriesApp#1]
Inside GroceryCategoryTableViewController change the addButtonWasPressed to the following:

-(void) addButtonWasPressed: (NSString *) category{

```
//create the Grocery Category Object
GroceryCategory *groceryCategory = [[GroceryCategory alloc]init];
groceryCategory.title = category;

// initialize the grocery items array here
groceryCategory.groceryItemsArray = [NSMutableArray array]; // THIS LINE

[_groceryCategoriesArray addObject:groceryCategory];

[self.tableView reloadData];
NSLog(@"%@", category);
```

 }

Now, inside GroceryItemsTableViewController use the self.selectedGroceryCategory.groceryItemsArray instead of initializing a new one.

**Comment by EARoa** [comment]
Thanks for the help!
